- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      start: installed

  - name: craeting app directory
    ansible.builtin.file: 
      path: /app 
      state: directory 

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: extarct code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: download dependencies
    community.general.npm:
      path: app/

  - name: copying service configuration
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

  - name: deamon reload
    ansible.builtin.systemd:
      deamon_relaod: true

  - name: start and enable catalogue service
    ansible.builtin.service:
      name: catalogue
      state: installed
      enabled: yes

  - name: copying mongo repo
    ansible.builtin.replace:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongo cleint server
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: installed

    - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0

